currentLang: "english"

broadcastWin: true
broadcastWinWorld: false
holographicRanking: false
lightnings: true
standingLimit: true
tpToLastLoc: false
snowballs: false
instantGiveShovel: false
randomSpawn: false
spectators: false
noScoreboard: false
sheepBonuses: true
diamondSpade: false
yamlStatistics: false
allowShowIP2: false
allowShowIPAsked2: false
serverIP: "nope"
disabledCommands:
checkForUpdates: true
snowballSheepBreakBlock: true

timer:
  start: 30
  blockStanding: 7

sql:
  tableName: "spleef"

reward:
  win: -1
  loose: -1

leaveItem:
  type: BARRIER
  data: 0

snowballsGivenOnBlockBreak: 4
snowballCooldown: 0
snowballMaxAmount: 16